version: '3'
services:
  mongo-rs0-1:
    image: mongo-start
    build: ./docker/mongo-rs0-1
    ports:
      - 27017:27017
    volumes:
      - ./docker/mongo-rs0-1/data:/data/db
    depends_on:
      - mongo-rs0-2
      - mongo-rs0-3

  mongo-rs0-2:
    image: mongo
    command: --replSet rs0
    ports:
      - 27018:27017
    volumes:
      - ./docker/mongo-rs0-2/data:/data/db

  mongo-rs0-3:
    image: mongo
    command: --replSet rs0
    ports:
      - 27019:27017
    volumes:
      - ./docker/mongo-rs0-3/data:/data/db

  setup-rs:
    image: setup-rs
    build: ./docker/setup
    depends_on:
      - mongo-rs0-1

  product-service:
    image: product-comparison-service
    ports:
      - 8083:8083
    depends_on:
      - mongo-rs0-1
